# Generated by Django 2.1.7 on 2023-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='RL_score',
            field=models.BigIntegerField(default=1000),
        ),
    ]
