# Generated by Django 2.1.7 on 2023-07-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userprofile_rl_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userSpan',
            field=models.TextField(default=''),
        ),
    ]
