# Generated by Django 2.1.7 on 2023-07-29 07:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20230728_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='RL_get',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
