# Generated by Django 2.1.7 on 2023-08-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_userprofile_scorespan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='scoreSpan',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userSpan',
            field=models.TextField(default='<span style="color:green;">|</span>'),
        ),
    ]
