# Generated by Django 2.1.7 on 2023-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='RL_add',
            field=models.BooleanField(default=False),
        ),
    ]
