# Generated by Django 2.1.7 on 2023-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20230813_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedetail',
            name='title',
            field=models.TextField(default='Unknow'),
        ),
    ]
