# Generated by Django 2.1.7 on 2023-08-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_animedetail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='state',
            new_name='status',
        ),
    ]
